apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-init-script
data:
  init.sh: |
    #!/bin/sh
    set -ex
    echo "===> Generating Guacamole DB schema (PostgreSQL)..."
    /opt/guacamole/bin/initdb.sh --postgresql > /init/01-guacamole.sql
    echo "âœ… Schema written to /init/01-guacamole.sql"
    ls -l /init
