apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: keycloak
      tfm/name: keycloak
      tfm/cluster-group: keycloak
    includeSelectors: true
components:
  - ../../../base/components/dev/keycloak/core
