apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: argocd
      tfm/name: argocd
      tfm/cluster-role: cluster-management
      tfm/cluster-group: argocd
    includeSelectors: true
components:
  - ../../../base/components/dev/argocd/core
