appPrefix: tfm
apps:
  argocd:
    autosync: false
    enabled: true
    prune: true
destination:
  name: tfm
source:
  envPath: k8s-cloud/tfm/dev
  repoUrl: git@github.com:juansanjose/TFM-redes.git
  targetRevision: main
